package com.miranda.car;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/miranda") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CarRepository carRepository;

    @PostMapping(path="/addcar") // Map ONLY POST Requests
    public @ResponseBody String addNewCar (
            @RequestParam String make,
            @RequestParam String model,
            @RequestParam String body,
            @RequestParam String transmission,
            @RequestParam String color,
            @RequestParam Double price) {

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Car c = new Car();
        c.setMake(make);
        c.setModel(model);
        c.setBody(body);
        c.setTransmission(transmission);
        c.setColor(color);
        c.setPrice(price);
        carRepository.save(c);
        return "Saved";
    }

    @GetMapping(path="/getcars")
    public @ResponseBody Iterable<Car> getAllCars() {
        // This returns a JSON or XML with the users
        return carRepository.findAll();
    }
    @DeleteMapping(path="/deletecars")
    public @ResponseBody String deleteCarById(@RequestParam int id) {
        // Delete the car by id
        carRepository.deleteById(id);

        // Return a response message
        return "Car with ID " + id + " deleted successfully";
    }

}